.TH SECRET 1
.SH NAME
secret \- send and recieve file trough icmp packets
.SH SYNOPSIS
.B secret
[\fB\-l\fR]
[\fB\-r\fR \fIFILENAME\fR]
[\fB\-s\fR \fISERVERNAME\fR|\fIIP\fR]
.SH DESCRIPTION
.B secret
send and recieve file troughc icmp echo request/reply packets.
Data in packets are encrypted using AES encryption
.SH OPTIONS
.TP
.BR -l
listen - start listening on any interface, decode and write all files catched

.TP
.BR \-r " " \fIFILENAME\fR
Set file to send. More than one file is supported.

.TP
.BR \-s " " \fISERVERNAME\fR|\fIIP\fR
Set server addres where file will be sent.